/**
 * Generate a llama-swap gateway config.yaml from a composer assignment.
 *
 * The assignment IS the full desired state, so the generated file contains only
 * the bricks that should be serving — one model entry per brick, routed to the
 * node/port it runs on. Each cmd has the idempotency guard used across the
 * hand-written config so llama-swap ADOPTS an already-running model (skips the
 * start) instead of reloading it, then attaches a health keeper. Groups are
 * derived from node placement (spark1 = swap, spark2 = co-resident).
 *
 * @param {import('./ModelCatalog.js').ModelCatalog} catalog
 * @param {Record<string,string[]>} assignment  { nodeId: [modelId,...] }
 * @returns {string} YAML
 */
export function generateLlamaSwapConfig(catalog, assignment) {
  // Collect unique bricks (dual models appear once, launched on their head node).
  const bricks = [];
  const seen = new Set();
  for (const node of Object.keys(assignment || {})) {
    for (const id of assignment[node] || []) {
      if (seen.has(id)) continue;
      const model = catalog.getModel(id);
      if (!model) continue;
      const launchNode = model.placement === "dual" ? Object.keys(model.launch || {})[0] : node;
      const spec = model.launch?.[launchNode];
      const ready = spec?.ready;
      if (!spec || !ready) continue;
      seen.add(id);
      bricks.push({ model, node, launchNode, spec, ready });
    }
  }

  const shArgs = (a) => (Array.isArray(a) ? a : []).join(" ").trim();
  const envPrefix = (env) =>
    env && typeof env === "object"
      ? Object.entries(env)
          .map(([k, v]) => `${k}=${v}`)
          .join(" ")
      : "";

  // A remote command string for the given launch node (ssh via the node's host).
  const remote = (spec, actionSpec) => {
    const parts = [envPrefix(spec.env), actionSpec.cmd, shArgs(actionSpec.args)].filter(Boolean);
    return `\${ssh2} "${parts.join(" ")}"`;
  };
  const local = (spec, actionSpec) => {
    const parts = [envPrefix(spec.env), actionSpec.cmd, shArgs(actionSpec.args)].filter(Boolean);
    return parts.join(" ");
  };

  const lines = [];
  lines.push("# GENERATED by sparkDash composer — edits are overwritten on the next Apply.");
  lines.push("healthCheckTimeout: 900");
  lines.push("logLevel: info");
  lines.push("");
  lines.push("macros:");
  lines.push(
    '  "ssh2": "ssh -o BatchMode=yes -o ConnectTimeout=10 -o ServerAliveInterval=10 -o ServerAliveCountMax=3 Spark2"'
  );
  lines.push("");
  lines.push("models:");

  const spark1Members = [];
  const spark2Members = [];

  for (const b of bricks) {
    const served = b.ready.servedModel || b.model.servedModel || b.model.id;
    const host = b.ready.host || "127.0.0.1";
    const port = b.ready.port;
    const base = `http://${host}:${port}`;
    const guard = `curl -fsS --max-time 4 ${base}/v1/models 2>/dev/null | grep -qF ${served}`;
    const keeper = `while curl -fsS --max-time 5 ${base}/v1/models >/dev/null 2>&1; do sleep 15; done`;
    const startCmd =
      b.spec.target === "ssh" ? remote(b.spec, b.spec.start) : local(b.spec, b.spec.start);
    const stopCmd =
      b.spec.target === "ssh" ? remote(b.spec, b.spec.stop) : local(b.spec, b.spec.stop);

    lines.push(`  "${served}":`);
    lines.push(`    cmd: bash -c '${guard} || { ${startCmd}; }; ${keeper}'`);
    lines.push(`    cmdStop: ${stopCmd}`);
    lines.push(`    proxy: "${base}"`);
    lines.push("    checkEndpoint: /v1/models");
    lines.push("");

    // Group by the node the brick physically serves on (its head node).
    if (b.launchNode === "spark2") spark2Members.push(served);
    else spark1Members.push(served);
  }

  // swap:false = the node's assigned models CO-RESIDE (each on its own unique
  // backend port; the composer's RAM check guarantees the set fits). llama-swap
  // routes each request to the right backend by name and keeps them all loaded,
  // so any RAM-fitting combination runs concurrently. (swap:true would evict
  // siblings on each request — wrong for a validated simultaneous set.)
  lines.push("groups:");
  for (const [group, members] of [
    ["spark1", spark1Members],
    ["spark2", spark2Members],
  ]) {
    if (!members.length) continue;
    lines.push(`  "${group}":`);
    lines.push("    swap: false");
    lines.push("    exclusive: false");
    lines.push("    members:");
    for (const m of members) lines.push(`      - "${m}"`);
  }
  lines.push("");

  return lines.join("\n");
}
