/**
 * Generate a llama-swap gateway config.yaml from a composer assignment.
 *
 * The assignment IS the full desired state, so the generated file contains only
 * the bricks that should be serving — one model entry per brick, routed to the
 * node/port it runs on. Each cmd has the idempotency guard used across the
 * hand-written config so llama-swap ADOPTS an already-running model (skips the
 * start) instead of reloading it, then attaches a health keeper. Groups are
 * derived from node placement (spark1 = swap, spark2 = co-resident).
 *
 * @param {import('./ModelCatalog.js').ModelCatalog} catalog
 * @param {Record<string,string[]>} assignment  { nodeId: [modelId,...] }
 * @returns {string} YAML
 */
export function generateLlamaSwapConfig(catalog, assignment) {
  // Collect unique bricks (dual models appear once, launched on their head node).
  const bricks = [];
  const seen = new Set();
  for (const node of Object.keys(assignment || {})) {
    for (const id of assignment[node] || []) {
      if (seen.has(id)) continue;
      const model = catalog.getModel(id);
      if (!model) continue;
      const launchNode = model.placement === "dual" ? Object.keys(model.launch || {})[0] : node;
      const spec = model.launch?.[launchNode];
      const ready = spec?.ready;
      if (!spec || !ready) continue;
      seen.add(id);
      bricks.push({ model, node, launchNode, spec, ready });
    }
  }

  const shArgs = (a) => (Array.isArray(a) ? a : []).join(" ").trim();
  // Escape for a double-quoted YAML scalar (descriptions are free text).
  const yamlStr = (v) => String(v).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  const envPrefix = (env) =>
    env && typeof env === "object"
      ? Object.entries(env)
          .map(([k, v]) => `${k}=${v}`)
          .join(" ")
      : "";

  // A remote command string for the given launch node (ssh via the node's host).
  const remote = (spec, actionSpec) => {
    const parts = [envPrefix(spec.env), actionSpec.cmd, shArgs(actionSpec.args)].filter(Boolean);
    return `\${ssh2} "${parts.join(" ")}"`;
  };
  const local = (spec, actionSpec) => {
    const parts = [envPrefix(spec.env), actionSpec.cmd, shArgs(actionSpec.args)].filter(Boolean);
    return parts.join(" ");
  };

  const lines = [];
  lines.push("# GENERATED by sparkDash composer — edits are overwritten on the next Apply.");
  lines.push("healthCheckTimeout: 900");
  lines.push("logLevel: info");
  lines.push("");
  lines.push("macros:");
  lines.push(
    '  "ssh2": "ssh -o BatchMode=yes -o ConnectTimeout=10 -o ServerAliveInterval=10 -o ServerAliveCountMax=3 Spark2"'
  );
  lines.push("");
  lines.push("models:");

  const spark1Members = [];
  const spark2Members = [];

  for (const b of bricks) {
    const served = b.ready.servedModel || b.model.servedModel || b.model.id;
    const host = b.ready.host || "127.0.0.1";
    const port = b.ready.port;
    const base = `http://${host}:${port}`;
    const guard = `curl -fsS --max-time 4 ${base}/v1/models 2>/dev/null | grep -qF ${served}`;
    const keeper = `while curl -fsS --max-time 5 ${base}/v1/models >/dev/null 2>&1; do sleep 15; done`;
    const startCmd =
      b.spec.target === "ssh" ? remote(b.spec, b.spec.start) : local(b.spec, b.spec.start);
    const stopCmd =
      b.spec.target === "ssh" ? remote(b.spec, b.spec.stop) : local(b.spec, b.spec.stop);

    lines.push(`  "${served}":`);
    lines.push(`    cmd: bash -c '${guard} || { ${startCmd}; }; ${keeper}'`);
    // cmdStop is deliberately a NO-OP. llama-swap issues cmdStop for every
    // *loaded* model when it reloads this file — and the composer rewrites this
    // file on every Apply. A real stop command there therefore tears down
    // models the composer just planned/started (observed: both spark2 servers
    // shut down within 1s of "reloading configuration"). Lifecycle belongs to
    // the composer, which owns the per-node memory budget; llama-swap only
    // routes. `cmd` above stays idempotent (it attaches to an already-serving
    // backend) so on-demand load still works.
    lines.push("    cmdStop: /usr/bin/true");
    if (stopCmd) lines.push(`    # composer stop (not used by llama-swap): ${stopCmd}`);
    lines.push(`    proxy: "${base}"`);
    lines.push("    checkEndpoint: /v1/models");

    // Advertise the model's real capabilities on GET /v1/models. llama-swap
    // SYNTHESISES that response from this config rather than proxying the
    // backend's, so without these a client sees no context limit or modality
    // and cannot size requests (vLLM's own max_model_len never reaches it).
    // `capabilities.context` surfaces as top-level `context_length`.
    const m = b.model;
    if (m.displayName) lines.push(`    name: "${yamlStr(m.displayName)}"`);
    if (m.description) lines.push(`    description: "${yamlStr(m.description)}"`);
    const ins = Array.isArray(m.inputs) && m.inputs.length ? m.inputs : ["text"];
    const outs = Array.isArray(m.outputs) && m.outputs.length ? m.outputs : ["text"];
    lines.push("    capabilities:");
    lines.push(`      in: [${ins.join(", ")}]`);
    lines.push(`      out: [${outs.join(", ")}]`);
    // Only assert tool calling where a tool parser is actually configured;
    // omitted when unverified rather than guessed.
    if (typeof m.tools === "boolean") lines.push(`      tools: ${m.tools}`);
    if (Number(m.maxContext) > 0) lines.push(`      context: ${Number(m.maxContext)}`);
    lines.push("    metadata:");
    lines.push(`      node: ${b.launchNode}`);
    lines.push(`      port: ${port}`);
    if (m.backend) lines.push(`      backend: ${m.backend}`);
    if (m.quant) lines.push(`      quantization: "${yamlStr(m.quant)}"`);
    if (Number(m.weightGB) > 0) lines.push(`      weightsGB: ${Number(m.weightGB)}`);
    lines.push(`      placement: ${m.placement === "dual" ? "dual (both nodes, TP=2)" : "single"}`);
    lines.push("");

    // Group by the node the brick physically serves on (its head node).
    if (b.launchNode === "spark2") spark2Members.push(served);
    else spark1Members.push(served);
  }

  // swap:false = the node's assigned models CO-RESIDE (each on its own unique
  // backend port; the composer's RAM check guarantees the set fits). llama-swap
  // routes each request to the right backend by name and keeps them all loaded,
  // so any RAM-fitting combination runs concurrently. (swap:true would evict
  // siblings on each request — wrong for a validated simultaneous set.)
  lines.push("groups:");
  for (const [group, members] of [
    ["spark1", spark1Members],
    ["spark2", spark2Members],
  ]) {
    if (!members.length) continue;
    lines.push(`  "${group}":`);
    lines.push("    swap: false");
    lines.push("    exclusive: false");
    lines.push("    members:");
    for (const m of members) lines.push(`      - "${m}"`);
  }
  lines.push("");

  return lines.join("\n");
}
